services:
  - type: worker
    name: reddit-ai-agent
    runtime: python
    plan: starter        # worker traži bar Starter plan
    branch: main
    rootDir: .
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - fromGroup: ai-secrets   # OPENAI_API_KEY, LANGCHAIN_API_KEY u ovoj grupi
      - key: WORDPRESS_URL
        sync: false
      - key: WORDPRESS_USERNAME
        sync: false
      - key: WORDPRESS_PASSWORD
        sync: false
