services:
  - type: worker
    name: reddit-ai-agent
    runtime: python
    plan: starter
    branch: main
    rootDir: .
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: python -u main.py
    envVars:
      - fromGroup: ai-secrets    # ako koristiš grupu za OPENAI/LANGCHAIN, nije obavezno
      - key: WORDPRESS_URL
        sync: false
      - key: WORDPRESS_USERNAME
        sync: false
      - key: WORDPRESS_PASSWORD
        sync: false
      - key: REDDIT_CLIENT_ID
        sync: false
      - key: REDDIT_CLIENT_SECRET
        sync: false
      - key: REDDIT_USER_AGENT
        sync: false
