services:
  - type: web
    name: reddit-ai-agent
    runtime: python
    envVars:
      - key: OPENAI_API_KEY
        fromGroup: ai-secrets
        required: true
      - key: LANGCHAIN_API_KEY
        fromGroup: ai-secrets
        required: true
      - key: WORDPRESS_URL
        fromSecret: WORDPRESS_URL
      - key: WORDPRESS_USERNAME
        fromSecret: WORDPRESS_USERNAME
      - key: WORDPRESS_PASSWORD
        fromSecret: WORDPRESS_PASSWORD
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    plan: free